name: ssevents_client
description: This implementation allows you to receive EventSource sent from the server.
version: 0.1.0
homepage: https://github.com/bronjham-code/sse_client

environment:
  sdk: '>=2.8.1 <3.0.0'

#dependencies:


#dev_dependencies:
  #test: ^1.14.4